// const HOST = "http://localhost:";
const HOST = "https://smart-classmate-server.onrender.com";
const PORT1 = "";
const PORT2 = "";

export const CHECK_LOGIN_API = HOST+PORT1+"/api/login/check";
export const ADD_LOGIN_API = HOST+PORT1+"/api/login/";
export const GET_STUDENT_LIST_API = HOST+PORT1+"/api/login/getStudent";
export const GET_STUDENT_DATA_API = HOST+PORT1+"/api/login/getStudProfileWithAllCourse";
export const GET_TEACHER_API = HOST+PORT1+"/api/login/getTeacher";
export const GET_USER_ID = HOST+PORT1+"/api/login/username";
export const ADD_TEACHER_API = HOST+PORT1+"/api/teacher";
export const MAIL_API = HOST+PORT1+"/api/mail/send-email";
export const CHANGE_TYPE_API = HOST+PORT2+"/api/login/changeType";
export const CHANGE_USER_STATUS_API = HOST+PORT1+"/api/login/change";
export const GET_COURSE_API = HOST+PORT1+"/api/courses";
export const GET_HAS_LEVEL_COURSE_API = HOST+PORT1+"/api/courses/getlevelCourses";
export const ADD_COURSE_API = HOST+PORT1+"/api/courses";
export const CHANGE_COURSE_API = HOST+PORT1+"/api/courses/update";
export const GET_STUDENT_COUNT_API = HOST+PORT1+"/api/login/getStudentCount";
export const ADD_LEVEL_API = HOST+PORT1+"/api/courselevels";
export const GET_LEVEL_API = HOST+PORT1+"/api/courselevels";
export const CHANGE_LEVEL_API = HOST+PORT1+"/api/courselevels/update";
export const FIND_COURSE_API = HOST+PORT1+"/api/courses/find";
export const FIND_COURSELEVELS_API = HOST+PORT1+"/api/courselevels/find";
export const GET_COURSE_LEVEL_API = HOST+PORT1+"/api/courselevels/getlevels";
export const ADD_TOPIC_API = HOST+PORT1+"/api/courseconcepts";
export const GET_TOPIC_API = HOST+PORT1+"/api/courseconcepts";
export const CHANGE_TOPIC_API = HOST+PORT1+"/api/courseconcepts/update";
export const GET_SHIFT_API = HOST+PORT2+"/api/shift";
export const ADD_STUDENT_API = HOST+PORT1+"/api/student";
export const GET_STUDENT_API = HOST+PORT1+"/api/student";
export const ADD_COURSEENROLL_API = HOST+PORT1+"/api/courseenrollment"; 
export const UPDATE_COURSEENROLL_API = HOST+PORT1+"/api/courseenrollment/update"; 
export const FIND_SHIFT_API = HOST+PORT2+"/api/shift/find";
export const ADD_EVENT_API = HOST+PORT1+"/api/events"
export const GET_EVENT_API = HOST+PORT1+"/api/events"
export const GET_HOLIDAY_API = HOST+PORT2+"/api/holidays"
export const CHANGE_HOLIDAY_API = HOST+PORT2+`/api/holidays/${PORT2=="8080"?"status":"update"}`
export const GET_UPCOMING_HOLIDAY_API = HOST+PORT1+"/api/holidays/upcoming"
export const GET_UPCOMING_EVENTS_API = HOST+PORT1+"/api/events/upcomingOne"
export const ATTENDANCE_API = HOST+PORT1+"/api/attendance"
export const TODAY_ATTENDANCE_API = HOST+PORT1+"/api/attendance/getToday"
export const UPDATE_ATTENDANCE_API = HOST+PORT1+"/api/attendance/update"
export const GET_STUDENT_ATTENDANCE_API = HOST+PORT1+"/api/attendance/student"